baseurl = "https://glencampbell.xyz/"
languageCode = "en-us"
title = "Glen Campbell"
uglyURLS = true
copyright = "2009-2026"
sectionPagesMenu = "main"
[markup.goldmark.renderer]
unsafe= true
[blackfriday]
fractions = false

[permalinks]
essay = "/essay/:year/:month/:contentbasename"
project = "/project/:contentbasename"
author = "/author/:contentbasename"
photo = "/photo/:year/:month/:contentbasename"

[params]
Description = "Fresh content served occasionally"
Author = "Glen Campbell"
mainSections = ["essay", "recipe"]

[[menu.main]]
identifier="author"
Weight=-1

[[menu.main]]
name="K6GEC"
identifier="k6gec"
url="/k6gec"
Weight=9

[[menu.main]]
name="Podcast"
identifier="podcast"
url="/podcast"
weight=3

[[menu.main]]
name="Essays"
identifier="essay"
url="/essay"
weight=1

[[menu.main]]
name="Projects"
identifier="project"
url="/project"
weight=8

[[menu.main]]
identifier="recipe"
name="Recipes"
weight=2
url="/recipe"
